# Generated by Django 5.0.3 on 2024-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
