# Generated by Django 5.0.3 on 2024-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
