# Generated by Django 5.0.3 on 2024-03-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
