# Generated by Django 5.0.3 on 2024-04-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_publisher_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
