# Generated by Django 5.0.4 on 2024-04-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
