# Generated by Django 5.0.3 on 2024-04-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_area_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapp.state'),
            preserve_default=False,
        ),
    ]
