# Generated by Django 5.0.3 on 2024-04-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_area_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
    ]
