# Generated by Django 5.0.3 on 2024-04-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_remove_area_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapp.country'),
            preserve_default=False,
        ),
    ]
