# Generated by Django 5.0.3 on 2024-04-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0016_area_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restapp.city'),
        ),
        migrations.AlterField(
            model_name='area',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restapp.country'),
        ),
        migrations.AlterField(
            model_name='area',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restapp.state'),
        ),
    ]
