# Generated by Django 5.0.3 on 2024-04-05 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0018_alter_area_city_alter_area_country_alter_area_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapp.student'),
            preserve_default=False,
        ),
    ]
