# Generated by Django 5.0.3 on 2024-04-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0019_area_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='student',
        ),
    ]
