# Generated by Django 5.0.3 on 2024-04-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0020_remove_area_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Areaname',
            new_name='areaname',
        ),
    ]
